package main;
import java.awt.Font;
import java.awt.event.ActionEvent;

import javax.swing.*;

public class LobbyGUI extends javax.swing.JFrame {

    private Client client;
    private LobbyRoom lobbyRoom;
    
    public LobbyRoom getLobbyRoom() {
    	return lobbyRoom;
    }

    /**
     * Creates new form LobbyGUI
     *
     * @param client to connect with
     */
    public LobbyGUI(Client client) {
        this.client = client;
        this.lobbyRoom = new LobbyRoom();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
        }
        //</editor-fold>
        initComponents();
        this.lblName.setText(client.getPlayer().getUsername());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void setupLobbyPanel() {
        try {

        } catch (Exception ex) {

        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLobby = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAountInfo = new javax.swing.JButton();
        btnJoinRoom0 = new javax.swing.JButton();
        btnLogOff = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnJoinRoom1 = new javax.swing.JButton();
        btnJoinRoom2 = new javax.swing.JButton();
        btnJoinRoom3 = new javax.swing.JButton();
        btnJoinRoom4 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        textField0 = new javax.swing.JTextField();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        textField3 = new javax.swing.JTextField();
        textField4 = new javax.swing.JTextField();
      
        btnRefreshRooms = new JButton(); 
        btnRefreshRooms.setFont(new Font("Segoe Script", 1, 12)); // NOI18N
        btnRefreshRooms.setText("Refresh Rooms");
        btnRefreshRooms.addActionListener(e -> refreshRooms(e)); 
        
      
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 1) {
        	textField0.setText("");
        }
        else {
        	textField0.setText(client.getLobbyRoom().getPlayersInRoom(0));
        	
        }
        
        textField1 = new javax.swing.JTextField();
        if (client.getLobbyRoom().getClientLobbyRoom().size() < 2) {
        	textField1.setText("");
        }
        else {
        	textField1.setText(client.getLobbyRoom().getPlayersInRoom(1));
        }

        textField2 = new javax.swing.JTextField();
        if (client.getLobbyRoom().getClientLobbyRoom().size() < 3) {
        	textField2.setText("");
        }
        else {
        	textField2.setText(client.getLobbyRoom().getPlayersInRoom(2));
        }
        
        textField3 = new javax.swing.JTextField();
        if (client.getLobbyRoom().getClientLobbyRoom().size() < 4) {
        	textField3.setText("");
        }
        else {
        	textField3.setText(client.getLobbyRoom().getPlayersInRoom(3));
        }
        
        textField4 = new javax.swing.JTextField();
        if (client.getLobbyRoom().getClientLobbyRoom().size() < 5) {
        	textField4.setText("");
        }
        else {
        	textField4.setText(client.getLobbyRoom().getPlayersInRoom(4));
        }

        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelLobby.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setText("Lobby");

        btnAountInfo.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnAountInfo.setText("Account Info");
        btnAountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAountInfoActionPerformed(evt);
            }
        });

        btnLogOff.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnLogOff.setText("Log Off");
        btnLogOff.addActionListener(evt -> btnLogOffActionPerformed(evt));

        btnJoinRoom0.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnJoinRoom0.setText("Join Room 0");
        btnJoinRoom0.addActionListener(evt -> btnJoinRoom(0));

        btnJoinRoom1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnJoinRoom1.setText("Join Room 1");
        btnJoinRoom1.addActionListener(evt -> btnJoinRoom(1));

        btnJoinRoom2.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnJoinRoom2.setText("Join Room 2");
        btnJoinRoom2.addActionListener(evt -> btnJoinRoom(2));

        btnJoinRoom3.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnJoinRoom3.setText("Join Room 3");
        btnJoinRoom3.addActionListener(evt -> btnJoinRoom(3));

        btnJoinRoom4.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnJoinRoom4.setText("Join Room 4");
        btnJoinRoom4.addActionListener(evt -> btnJoinRoom(4));

        lblName.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name Here");

        javax.swing.GroupLayout panelLobbyLayout = new javax.swing.GroupLayout(panelLobby);
        panelLobby.setLayout(panelLobbyLayout);
        panelLobbyLayout.setHorizontalGroup(
            panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLobbyLayout.createSequentialGroup()
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLobbyLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLobbyLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLobbyLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(btnRefreshRooms, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE) 
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(142, 142, 142)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLobbyLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField1)
                            .addComponent(textField0)
                            .addComponent(textField2)
                            .addComponent(textField3)
                            .addComponent(textField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJoinRoom0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJoinRoom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJoinRoom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJoinRoom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJoinRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        panelLobbyLayout.setVerticalGroup(
            panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAountInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshRooms) 
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinRoom0)
                    .addComponent(textField0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinRoom1)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinRoom2)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinRoom3)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinRoom4)
                    .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOff)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAountInfoActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    setVisible(false);
                    dispose();
                    new AccountInfoGUI(client).setupAccountInfoPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnAountInfoActionPerformed

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    setVisible(false);
                    dispose();
                    new ConnectGUI(client).setupConnectPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnLogOffActionPerformed

    private void btnJoinRoom(int roomNumber) {//GEN-FIRST:event_btnJoinRoom0ActionPerformed
        // TODO add your handling code here:
        try {
            if (client.getRoom().getNumOfPlayers() < client.getRoom().getMAXPLAYERS()) {
                this.lobbyRoom.addPlayer(roomNumber, client.getPlayer().getUsername());
                this.client.joinRoom(roomNumber);
                client.joinRoom(roomNumber);
                new GameRoomGUI().setupGameRoom(client);
                setVisible(false);
                dispose();
            } else {
                JOptionPane.showMessageDialog(panelLobby, "Room is full!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelLobby, "Unable to join room!");

        }
    }//GEN-LAST:event_btnJoinRoom0ActionPerformed
    
    public void refreshRooms(ActionEvent evt) {
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 1) {
        	textField0.setText("");
        }
        else {
        	textField0.setText(client.getLobbyRoom().getPlayersInRoom(0));
        }
    	
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 2) {
        	textField1.setText("");
        }
        else {
        	textField1.setText(client.getLobbyRoom().getPlayersInRoom(1));
        }
    	
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 3) {
        	textField2.setText("");
        }
        else {
        	textField2.setText(client.getLobbyRoom().getPlayersInRoom(2));
        }
    	
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 4) {
        	textField3.setText("");
        }
        else {
        	textField3.setText(client.getLobbyRoom().getPlayersInRoom(3));
        }
    	
    	if (client.getLobbyRoom().getClientLobbyRoom().size() < 5) {
        	textField4.setText("");
        }
        else {
        	textField4.setText(client.getLobbyRoom().getPlayersInRoom(4));
        }
    	
    	System.out.println(client.getLobbyRoom().getPlayersInRoom(0));
    	revalidate();
        repaint();
        setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	try {
                Client client = new Client();
                client.setPlayer(new Player("Samira", 1000));
                new LobbyGUI(client).setupLobbyPanel();
            	} catch(Exception ex) {}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAountInfo;
    private javax.swing.JButton btnJoinRoom0;
    private javax.swing.JButton btnJoinRoom1;
    private javax.swing.JButton btnJoinRoom2;
    private javax.swing.JButton btnJoinRoom3;
    private javax.swing.JButton btnJoinRoom4;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel panelLobby;
    private javax.swing.JTextField textField0;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField textField3;
    private javax.swing.JTextField textField4;
    private JButton btnRefreshRooms;
    // End of variables declaration//GEN-END:variables
}