
public class BlackjackGUI extends javax.swing.JFrame {

    private Client client;
    private ConnectGUI connectGUI;
    private RegisterOrLoginGUI registerOrLoginGUI;
    private LoginGUI loginGUI;
    private RegisterGUI registerGUI;
    private LobbyGUI lobbyGUI;
    private AccountInfoGUI accountInfoGUI;
    private GameRoomGUI gameRoomGUI;

    /**
     * Creates new form BlackjackGUI
     */
    public BlackjackGUI(Client client) {
        this.client = client;
        this.connectGUI = new ConnectGUI(client);
        this.registerOrLoginGUI = new RegisterOrLoginGUI(client);
        this.loginGUI = new LoginGUI(client);
        this.registerGUI = new RegisterGUI(client);
        this.lobbyGUI = new LobbyGUI(client);
        this.accountInfoGUI = new AccountInfoGUI(client);
        this.gameRoomGUI = new GameRoomGUI(client);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void setupBlackjackPanel() {
        try {

        } catch (Exception ex) {

        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnShowRegisterOrLoginGUI = new javax.swing.JButton();
        btnShowConnectGUI = new javax.swing.JButton();
        btnShowLoginGUI = new javax.swing.JButton();
        btnShowRegisterGUI = new javax.swing.JButton();
        btnShowLobbyGUI = new javax.swing.JButton();
        btnShowAccountInfoGUI = new javax.swing.JButton();
        btnShowGameRoomGUI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setText("Blackjack");

        btnShowRegisterOrLoginGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowRegisterOrLoginGUI.setText("Show Register Or Login GUI");
        btnShowRegisterOrLoginGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRegisterOrLoginGUIActionPerformed(evt);
            }
        });

        btnShowConnectGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowConnectGUI.setText("Show Connect GUI");
        btnShowConnectGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowConnectGUIActionPerformed(evt);
            }
        });

        btnShowLoginGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowLoginGUI.setText("Show Login GUI");
        btnShowLoginGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoginGUIActionPerformed(evt);
            }
        });

        btnShowRegisterGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowRegisterGUI.setText("Show Register GUI");
        btnShowRegisterGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRegisterGUIActionPerformed(evt);
            }
        });

        btnShowLobbyGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowLobbyGUI.setText("Show Lobby GUI");
        btnShowLobbyGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLobbyGUIActionPerformed(evt);
            }
        });

        btnShowAccountInfoGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowAccountInfoGUI.setText("Show Account Info GUI");
        btnShowAccountInfoGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAccountInfoGUIActionPerformed(evt);
            }
        });

        btnShowGameRoomGUI.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        btnShowGameRoomGUI.setText("Show Game Room GUI");
        btnShowGameRoomGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGameRoomGUIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnShowConnectGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowRegisterOrLoginGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowLoginGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowRegisterGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowLobbyGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowAccountInfoGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowGameRoomGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowConnectGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowRegisterOrLoginGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowLoginGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowRegisterGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowLobbyGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowAccountInfoGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowGameRoomGUI)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAccountInfoGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAccountInfoGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    accountInfoGUI.setupAccountInfoPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowAccountInfoGUIActionPerformed

    private void btnShowConnectGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowConnectGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    connectGUI.setupConnectPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowConnectGUIActionPerformed

    private void btnShowLobbyGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLobbyGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    lobbyGUI.setupLobbyPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowLobbyGUIActionPerformed

    private void btnShowRegisterOrLoginGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRegisterOrLoginGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    registerOrLoginGUI.setupRegisterOrLoginPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowRegisterOrLoginGUIActionPerformed

    private void btnShowLoginGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoginGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    loginGUI.setupLoginPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowLoginGUIActionPerformed

    private void btnShowRegisterGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRegisterGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    registerGUI.setupRegisterPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowRegisterGUIActionPerformed

    private void btnShowGameRoomGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGameRoomGUIActionPerformed
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //setVisible(false);
                    //dispose();
                    gameRoomGUI.setupGameRoomPanel();
                }
            });
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnShowGameRoomGUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Client client = new Client();
                client.setPlayer(new Player("Samira", "Mehroz", "samira123", 1000));
                new BlackjackGUI(client).setupBlackjackPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowAccountInfoGUI;
    private javax.swing.JButton btnShowConnectGUI;
    private javax.swing.JButton btnShowGameRoomGUI;
    private javax.swing.JButton btnShowLobbyGUI;
    private javax.swing.JButton btnShowLoginGUI;
    private javax.swing.JButton btnShowRegisterGUI;
    private javax.swing.JButton btnShowRegisterOrLoginGUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
